### ISSUE TITLE
Non-panicking mode

### ISSUE THREAD

**Issue by vi** [oli-obk/rust-si#7]
Can there be a macro that returns some Err instead of panicking?

```
fn handle_input(x: String) -> Result<i64, ()> {
    Ok(scan!(x, "MyValue(id={:x})"))
}
```

**Comment by oli-obk** [comment]
I'd rather set it up so the macro returns a `Result` directly, then you can choose to use `try!` or something else directly.

**Comment by vi** [comment]
Good idea, like in a competing crate.

**Comment by alexmbird** [comment]
Now my code builds, +1 for this.

I'm writing a small [utility](https://github.com/alexmbird/sleepuntil) which can accept a string representing the time in various different formats.  My intention is to try parsing in various formats in turn until one 'fits'.  Right now it panics on the first so it'd be very helpful to get a `Result` to check.

**Comment by oli-obk** [comment]
There's no guarantee that all the `scan!` variables have been set, if the command fails in the middle. So if `scan!` returned a result, then you'd never be able to access the variables, because they might be uninitialized. Rust can't compile the following yet:

```rust
    let a;
    if b {
        a = 5;
    }
    if b {
        Ok(a) // use of possibly uninitialized variable: `a`
    } else {
        Err(())
    }
```

We can require all `scan!` arguments to be results, so you'd need to check every single value, and might get partial results (some arguments set, some not).

```rust
let maybe_i: Result<i32, _>; // _ is actually `std::str::FromStr<i32>::Err`
scan!("number: {}", maybe_i);
```

**Comment by oli-obk** [comment]
Maybe the [`scan_rules`](http://stackoverflow.com/a/35860619/1103681) crate fits your usecase more?

**Comment by alexmbird** [comment]
I saw `scan_rules` but it lacks the `try_scan!` macro I'd need.  `let_scan!` looks close but again, it'll panic the first time a string doesn't match.

**Comment by oli-obk** [comment]
huh? the `readln!` macro can do this panic-less according to the stackoverflow answer
